name: customerparkapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  clipboard: ^0.1.3
  cloud_firestore: ^5.6.1
  country_code_picker: ^3.1.0
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  date_picker_timeline: ^1.2.6
  dotted_border: ^2.1.0
  firebase_app_check: ^0.3.2
  firebase_auth: ^5.4.0
  firebase_database: ^11.3.0
  firebase_storage: ^12.3.7
  flutter_easyloading: ^3.0.5
  flutter_email_sender: ^6.0.3
  flutter_html: any
  flutter_local_notifications: ^18.0.1
  flutter_osm_plugin: any
  flutter_polyline_points: ^2.1.0
  flutter_rating_bar: ^4.0.1
  flutter_stripe: ^11.1.0
  flutter_svg: ^2.0.10+1
  geocoding: any
  geolocator: any
  get: ^4.6.6
  google_maps_flutter: any
  google_maps_place_picker_mb: any
  google_sign_in: ^6.2.1
#  google_api_headers: any
  googleapis_auth: any
  image_picker: ^1.1.2
  intl: ^0.19.0
  location: ^7.0.1
  map_launcher: ^3.5.0
  mobile_scanner: ^6.0.2
  osm_nominatim: ^3.0.1
  pin_code_fields: ^8.0.1
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  razorpay_flutter: ^1.3.7
  share_plus: ^10.0.2
  shared_preferences: ^2.3.2
  sign_in_with_apple: ^6.1.3
  syncfusion_flutter_datepicker: ^28.1.38
  timer_count_down: ^2.2.2
  url_launcher: ^6.3.0
  uuid: ^4.5.1
  google_api_headers: ^2.0.3

dependency_overrides:
  webview_flutter: any
  http: ^1.2.2
  firebase_messaging: any
  firebase_core: any

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: GolosText-Regular
      fonts:
        - asset: assets/fonts/GolosText-Regular.ttf

    - family: GolosText-Medium
      fonts:
        - asset: assets/fonts/GolosText-Medium.ttf

    - family: GolosText-Black
      fonts:
        - asset: assets/fonts/GolosText-Black.ttf

    - family: GolosText-Bold
      fonts:
        - asset: assets/fonts/GolosText-Bold.ttf

    - family: GolosText-ExtraBold
      fonts:
        - asset: assets/fonts/GolosText-ExtraBold.ttf

    - family: GolosText-SemiBold
      fonts:
        - asset: assets/fonts/GolosText-SemiBold.ttf

  assets:
    - assets/images/
    - assets/icon/
    - assets/json/
    - assets/fonts/
